import type { MetadataRoute } from "next";

// ЗМІНИ на реальний production-домен перед деплоєм, якщо він відрізняється.
const BASE_URL = "https://rabbit-farming-from-a-to-z-react.vercel.app";

// Публічні сторінки-статті (без гейту на сесію, без службових/особистих сторінок).
// Список збережено з попереднього sitemap.xml Vite-проєкту.
// ДОДАНО 4 сторінки контенту, які існують у коді, але не потрапили в
// попередній sitemap.xml (ймовірно, додані вже після його останньої генерації):
// rabbit-allergy, rabbits-and-children, telegony, insurance-grants.
const CONTENT_PAGES = [
    "anesthesia-care",
    "antibiotic-therapy",
    "apartment-proofing",
    "artificial-feeding",
    "artificial-insemination",
    "beginner-guide",
    "beginner-mistakes",
    "biology",
    "biosecurity",
    "breed-standards",
    "breeding",
    "breeding-evaluation",
    "breeding-herd",
    "breeds",
    "buck-management",
    "buying-rabbit",
    "calendar",
    "care",
    "climate-automation",
    "coat-colors-evaluation",
    "companion-bonding",
    "composting",
    "compound-feed",
    "crops",
    "culling",
    "diet-therapy",
    "diseases",
    "disinfection",
    "disqualifying-faults",
    "doe-preparation",
    "dosage-calculator",
    "droppings",
    "drug-compatibility",
    "economics",
    "enclosure",
    "enrichment",
    "equipment",
    "false-pregnancy",
    "faq",
    "farm-management-software",
    "farm-monitoring",
    "feeders",
    "feeding",
    "feeding-automation",
    "first-aid",
    "floor-care",
    "fur-evaluation",
    "fur-processing",
    "genetics",
    "glossary",
    "grooming",
    "group-housing",
    "heat-stroke",
    "insurance-grants", // додано — відсутнє у старому sitemap.xml
    "lab-diagnostics",
    "leaves",
    "legal",
    "litter-training",
    "mating-behavior",
    "mating-frequency",
    "medicines",
    "microclimate",
    "necropsy",
    "neutering",
    "new-food",
    "okril",
    "okril-control",
    "pain-management",
    "parasites",
    "pedigree-records",
    "pet-travel",
    "pit-keeping",
    "poisoning",
    "predators",
    "profit-calculator",
    "rabbit-allergy", // додано — відсутнє у старому sitemap.xml
    "rabbit-behavior-problems",
    "rabbit-body-condition",
    "rabbit-body-language",
    "rabbit-conformation",
    "rabbit-housing-diy",
    "rabbit-myths",
    "rabbit-sounds",
    "rabbit-stress",
    "rabbit-vs-hare",
    "rabbit-whiskers",
    "rabbits-and-chickens",
    "rabbits-and-children", // додано — відсутнє у старому sitemap.xml
    "rabbits-and-guinea-pigs",
    "rabbits-and-predators",
    "recipes",
    "replacement-stock",
    "sales",
    "seasonal-autumn",
    "seasonal-molting",
    "seasonal-spring",
    "seasonal-summer",
    "select-buck",
    "select-doe",
    "selection",
    "senior-rabbit",
    "sexing",
    "show-judging",
    "show-preparation",
    "show-scoring",
    "slaughter",
    "smart-farm",
    "special-feeds",
    "symptoms",
    "telegony", // додано — відсутнє у старому sitemap.xml
    "tips",
    "tools",
    "transport",
    "treatment",
    "treatment-log",
    "vaccinations",
    "vet-fecal-sample",
    "vet-injections",
    "vet-oral-meds",
    "vet-temperature",
    "water",
    "water-medication",
    "weaning",
    "weight-control",
    "winter-litter",
    "zoonoses",

    // УВАГА: у старому sitemap.xml "/calculator" був присутній, хоча ця
    // сторінка вимагає авторизації (гейт на сесію). Залишено тут для
    // збереження попередньої поведінки — вирішіть, чи прибрати її, раз
    // неавторизований відвідувач з пошуку однаково побачить форму входу.
    "calculator",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
    const now = new Date();

    return [
        {
            url: BASE_URL,
            lastModified: now,
            changeFrequency: "weekly",
            priority: 1.0,
        },
        ...CONTENT_PAGES.map((slug) => ({
            url: `${BASE_URL}/${slug}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.8,
        })),
    ];
}